version: "3.8"

services:
  frontend:
    build: /frontend
    ports:
      - "5173:5173"
    networks:
      - chat-app

  backend:
    build: /backend
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    networks:
      - chat-app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - chat-app

networks:
  chat-app:

volumes:
  mongo-data:
